# Playing with Ginger in Hector's

## Ortholog detection in Sylvio/G-strain

Reciprocal best hit.  Even at identity < 30%
The excel sheet describing how the different genes are eliminated from
the total gene population is really confusing.
I think that maybe a flowchart would help with the
starting->operation->ending numbers would help?

Concerns about what happens to the final data when switching from
decisions based on ~11k genes versus 4.5k genes after this filtering
operation.

What to do when dealing with groups of reciprocal best hits which are
2:2 or more?  Sum the raw counts and merge the genes?  Average them?
Keep them separate?

Separately, perform timea/timeb analyses of the two species, then
compare gene lists.
Similarly, perform DE analyses of the ~5k genes which behave well with
respect to reciprocal best hit/identity/whatever - then perform again
with the whole set -- finally look to see that the expression
distribution follows the rules that one would expect.  MA plot is the
most fundamental in this analysis -- I am not sure why yet, but
evidently the shape of that is known when they are similar.

Perform fisher log(odd ratio) with respect to FDR until they hit a log
odd ratio == 0 (in this case thhis was at 0.35)

Scatter plots of logFC/t stats/B stats for 24/72 hours.  Fix the axes
on these to match the largest range, this way you can see the shift in
distribution from one to the other.

plotting logFC across times shows it not quite following the identity
line -- its skewed.  The t-statistics do the same thing.  This is good
because if they followed different lines then it would indicate a
problem with the t-statistic generation.  The B is log-odds value that
each gene is differentially expressed from eBayes.  Plotting one vs
the other doesn't give a distribution which follows a line at all.

The scatter of logFC turns out to be interesting alongside the t,
because it shows that the estimation process is not causing the skew
and therefore that skew is more likely to be biological.


```{r orthologr}

install_github("HajkD/orthologr", build_vignettes = TRUE, dependencies = TRUE)

## affy::ma.plot(a, m, plot.method="smoothScatter", lwd=1.3)

```
