## Time-stamp: <Sun Mar 13 17:30:20 2016 Ashton Trey Belew (abelew@gmail.com)>

#' @name annotations
#' @title Streptococcus pyogenes 5005 annotation data taken from microbesonline.org
#' @description This data set results from an import.gff call
#' @docType data
#' @usage annotations
#' @format a \code{data.frame} instance, 1 row per annotation.
#' @source microbesonline.org
#' @author atb
#' @export
NULL

#' @name color_hash
#' @title colors provided to hpgltools for plotting
#' @description A hash of color to sample names
#' @docType data
#' @usage color_hash
#' @format a \code{hash} instance
#' @source the hash package
#' @author atb
#' @export
NULL

#' @name colors
#' @title colors provided to hpgltools for plotting
#' @description A hash of color to sample names, this is
#' redundant and either this or color_hash should be removed
#' @docType data
#' @usage color_hash
#' @format a \code{data.frame} instance
#' @source the hash package
#' @author atb
#' @export
NULL

#' @name early_late
#' @title an expt superclass of early vs. late 5005 samples in thy media
#' @description Generated by running create_expt() with a sample sheet
#' and extracting only the early vs. late samples.
#' @docType data
#' @usage summary(early_late)
#' @format a \code{expt} instance
#' @source the create_expt()
#' @author atb
#' @export
NULL
